apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: instances.k8s.truebrain.nl
spec:
  group: k8s.truebrain.nl
  version: v1
  scope: Namespaced
  names:
    plural: instances
    singular: instance
    kind: Instance
    shortNames:
     - ins
